name: "CI/CD : Test Source & Déploiement Terraform"

on:
  push:
    branches: [ "main" ]

jobs:
  # 1. CI : Tests de qualité du code source
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Adapté pour cibler le nouveau dossier src/
      - name: Vérifier la syntaxe HTML
        run: npx htmlhint src/index.html

  # 2. CD : Déploiement de l'Infrastructure AWS
  deploy-infra:
    needs: lint-and-test # Ne se lance que si le code HTML est valide
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra # Terraform s'exécute uniquement dans son dossier
        
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installation de Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialisation (Init)
        run: terraform init

      - name: Déploiement automatique (Apply)
        run: terraform apply -auto-approve -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    
      
      - name: Transfert des fichiers web vers AWS (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: admin # À adapter selon l'OS de ton VPS AWS (ex: 'debian', 'ubuntu' ou 'admin')
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "src/*"
          target: "/tmp/web_files"
          strip_components: 1 # Retire le dossier parent "src/" lors de la copie

      - name: Installation dans Nginx (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: admin # Même utilisateur qu'au-dessus
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Déplacement des fichiers vers le dossier Nginx avec les droits admin
            sudo mkdir -p /var/www/html
            sudo cp -r /tmp/web_files/* /var/www/html/
            
            # Nettoyage et redémarrage
            sudo rm -rf /tmp/web_files
            sudo systemctl reload nginx