name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  
  # 1. CI : Tests de qualité de code

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Vérifier la syntaxe HTML
        run: npx htmlhint index.html


  # 2. BUILD & PUSH (Exécuté SEULEMENT si la CI passe)

  build-and-push:
    needs: lint-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Connexion au registre GitHub Container (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extraire les métadonnées (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=

      - name: Build et Push de l'image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
# --- AJOUT SÉCURITÉ (DEVSECOPS) 
      - name: Scan de vulnérabilités Docker (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/stefmih/projet1b3devops:latest
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

  # 3. CD : DÉPLOIEMENT SUR VPS & VÉRIFICATION

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Connexion SSH et déploiement sur le VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ghcr.io/stefmih/projet1b3devops:latest
            docker stop mon-site || true
            docker rm mon-site || true
            docker run -d --name mon-site --restart always -p 20000:80 ghcr.io/stefmih/projet1b3devops:latest
            docker image prune -f

      - name: Smoke Test (Vérification live du site)
        run: |
          sleep 5
          curl -I --fail https://devops.pokeban.org
